#!/bin/bash

	for (( i=0; i<${2-5}; i++ )); do
	head -c ${1-10} /dev/random | base64 | sed 's/==$//'
	done
#head -c ${1-10} /dev/random | base64 | sed 's/==$//'
#head -c ${1-10} /dev/random | base64 | sed 's/==$//'
#head -c ${1-10} /dev/random | base64 | sed 's/==$//'
#head -c ${1-10} /dev/random | base64 | sed 's/==$//'
