#!/bin/bash

# Requires: php-pear-PhpDocumentor, php-Smarty2

: ${1?"Usage: `basename $0` dir_to_process,dir2,dir3"}

#phpdoc -f /var/www/_SHARED_/debug.php -t /var/www/temp/DOCS/ -s -o HTML:Smarty:PHP
phpdoc -d "$1" -t _phpdocs --undocumentedelements on \
	--title "Pavel Alexeev aka Pahan-Hubbitus framework documentation" \
	--customtags 'changelog' --sourcecode on \
	--ignore '_phpdocs,.git,.svn,_phpdocs.log' \
	-s -o HTML:Smarty:PHP 2>&1 | tee _phpdocs.log