#!/bin/sh

ps ax -o pid,state,ppid | \
	fgrep ' Z ' | \
		while read pid state ppid; do
			if [ $ppid -eq 1 ]; then
				echo "Zombie process $pid have parent 1. Skiping kill init!"
			else
				echo "Kill process $pid with parent $ppid";
				kill $ppid;
			fi
		done
