#!/bin/bash

: ${1?"You must provide at least package-name.src.rpm: `basename $0` package.src.rpm"}

set -e

	for branch in f30 f32 epel7 epel8; do
	echo "Try build for ===${branch}==="
	koji build --scratch $branch $@
	# fedpkg --release $branch scratch-build --srpm $@
	done