#!/bin/bash

cd /home/pasha/imus/IdeaProjects/imus-trunk/lib/antinform-domain/

rm -f target/antinform-domain-*-SNAPSHOT.jar ; mdep && \
	cp -fb target/antinform-domain-*-SNAPSHOT.jar /home/pasha/imus/fileSets/jar/ && \
	cp -fb target/antinform-domain-*-SNAPSHOT.jar /mnt/net/p/users/Pasha/jar/

rm -f /home/pasha/imus/IdeaProjects/imus/ascug-maket/ascug-esb-modules/imus-esb-core/target/dep/antinform-domain-*-SNAPSHOT.jar
cp -fb target/antinform-domain-*-SNAPSHOT.jar /home/pasha/imus/IdeaProjects/imus/ascug-maket/ascug-esb-modules/imus-esb-core/target/dep/
