#!/bin/bash

. ~/.config/repomirror/repomirror.conf

: ${LOCAL_REPO_DIR?'You must provide env var LOCAL_REPO_DIR - local root of repo (directly or in config ~/.config/repomirror/repomirror.conf)!'}
: ${REPOS?'You must provide env var REPOS - subdirs to sync (directly or in config ~/.config/repomirror/repomirror.conf)!'}
: ${LOGFILE?'You must provide env var LOGFILE (directly or in config ~/.config/repomirror/repomirror.conf)!'}

############################################################

function repoUpdate(){
#$1 - In repodir.
#$2 - Out dir where placed repodata directory
#$3 - Logfile.

# --checksum sha for compatability with EPEL5
# xz compression type is not supported by COPR - http://copr-be.cloud.fedoraproject.org/results/hubbitus/test/fedora-20-x86_64/python-nbxmpp-0.4-1.fc20/root.log
nice -n 19 createrepo_c --update --checksum sha -d -o "$1" "$2" | tee -a "$3"
}

	for distr in ${REPOS[*]}
	do
		pushd "$LOCAL_REPO_DIR/$distr"
		repoUpdate ./ ./ "$LOGFILE"
		echo $distr" DONE"

		nice -n 19 \
			lftp -c 'open -e "mirror -caveR \
				--exclude=.htaccess \
				--exclude=header.htm \
				--delete-first \
				'"$LOCAL_REPO_DIR/$distr"' '"hubbitus.info/rpm/$distr"'" \
					ftp.hubbitus.org' | tee "$LOGFILE"

		popd
	done

echo 'Repo updated'
