#!/bin/bash

#LOCAL_REPO_DIR=/mnt/virtuals/Hubbitus.Repo/
LOCAL_REPO_DIR=/mnt/Media/Hubbitus.Repo/

# All
#REPOS=( $( ls "$LOCAL_REPO_DIR" ) )
# Fresh
REPOS=( Fedora19 Fedora18 EL5 EL6 )

############################################################

function repoUpdate(){
#$1 - In repodir.
#$2 - Out dir where placed repodata directory
#$3 - Logfile.

# Due to BUG https://bugzilla.redhat.com/show_bug.cgi?id=449201 use option -C is not possible now
# New BUG - https://bugzilla.redhat.com/show_bug.cgi?id=512610
# --checksum sha for compatability with EPEL5
nice -n 19 createrepo --update --checksum sha -Cvpd -o "$1" "$2" | tee -a "$3"
#nice -n 19 createrepo -vpd -o "$1" "$2" | tee -a "$3"
}

	for distr in ${REPOS[*]}
	do
	pushd "$LOCAL_REPO_DIR/$distr"
	repoUpdate ./ ./ "/home/pasha/repomirror.log"
	echo $distr" DONE"
	popd
	done

#	--script=/home/pasha/lftp.mirror.script \

nice -n 19 \
	lftp -c 'open -e "mirror -caveR \
		--exclude=.htaccess \
		--exclude=header.htm \
		--delete-first \
		--log=/home/pasha/lftp_mirror.log \
		'"$LOCAL_REPO_DIR"' hubbitus.info/rpm" \
			ftp.hubbitus.org' | tee /home/pasha/lftp_mirror.log
echo 'Repo updated'

#RSYNC_SHARED_OPTIONS='-arlDSzv --stats --human-readable --partial --progress --itemize-changes'
#rsync $RSYNC_SHARED_OPTIONS --delete -e 'ssh -p 2222' "$LOCAL_REPO_DIR" 'hubbitus@hubbitus.net.ru:/home/hubbitus/_SITES/hubbitus.net.ru/rpm/' | tee /home/pasha/rsync_mirror.log
#rsync $RSYNC_SHARED_OPTIONS --delete "$LOCAL_REPO_DIR" "host1plus:/home/cookeeor/domains/hubbitus.info/public_html/rpm/" | tee /home/pasha/rsync_mirror.log
