#!/bin/bash

	if [ $SECONDS -lt 2 ]; then
	echo "This script must be sourced ('. $0') instead of simple run. Exiting."
	exit
	fi

#echo -=SSH_AUTH_SOCK=$( ls /tmp/ssh-*/agent.* )=-
export SSH_AUTH_SOCK=$( ls /tmp/ssh-*/agent.* )
