#!/bin/bash

: ${1?"You should provide at least 1 argument: `basename $0` target-ssh-host [<remote capture parameters and filters>]"}

HOST="$1"
shift

ssh "$HOST" "tshark -iany -w- $@"| wireshark -k -i-
