#!/usr/bin/bash

source $(dirname $(realpath "$0"))/.shared

: ${1?"$(usage "Not enough arguments: $(basename $0) <var1> [var2, var3...]")"}

for _var in "$@"; do
    _val="$($(dirname $(realpath "$0"))/get ${_var})" || {
        echo "Failed to get secret: ${_var}" >&2
        exit 1
    }
    echo "export ${_var}=\"${_val}\""
done
