#!/usr/bin/bash

source $(dirname $(realpath "$0"))/.shared

: ${1?"$(usage "Not enough arguments: `basename $0` <var1> [var2, var3...]")"}
readonly VAR="${1}"

for _var in "$@"; do
    echo "export ${_var}=\"$($(dirname $(realpath "$0"))/get ${_var})\""
done
