#!/usr/bin/bash

source $(dirname $(realpath "$0"))/.shared

: ${1?"$(usage "Not enough arguments: `basename $0` <var> <value>")"}
readonly VAR="${1}"

pass show "${SECRET_STORE_PREFIX}/${PROJECT}/${ENV}/${VAR}"
