#!/usr/bin/bash

source $(dirname $(realpath "$0"))/.shared

: ${1?"$(usage "Not enough arguments: `basename $0` <var> <value>")"}
readonly VAR="${1}"
: ${2?"$(usage "Not enough arguments: `basename $0` <var> <value>")"}
readonly VAL="${2}"

set -x

# Backup old value, if present
[[ 'true' == "${SECRET_BACKUP}" ]] && pass mv "${SECRET_STORE_PREFIX}/${PROJECT}/${ENV}/${VAR}" "${SECRET_STORE_PREFIX}/${PROJECT}/${ENV}/${VAR}.BAK.$(date --iso-8601=ns)" 2>/dev/null

echo -n "${VAL}" | pass insert "${SECRET_STORE_PREFIX}/${PROJECT}/${ENV}/${VAR}" --multiline 1>/dev/null
