#!/usr/bin/bash

source $(dirname $(realpath "$0"))/.shared

: ${1?"$(usage "Not enough arguments: $(basename $0) <var> <value>")"}
readonly VAR="${1}"
: ${2?"$(usage "Not enough arguments: $(basename $0) <var> <value>")"}
readonly VAL="${2}"

[[ "${SECRET_DEBUG}" ]] && set -x

# Backup old value, if present
[[ 'true' == "${SECRET_BACKUP}" ]] && pass mv "${SECRET_STORE_PREFIX}/${PROJECT}/${ENV}/${VAR}" "${SECRET_STORE_PREFIX}/${PROJECT}/${ENV}/${VAR}.BAK.$(date --iso-8601=ns)" &>/dev/null || true

echo -n "${VAL}" | pass insert "${SECRET_STORE_PREFIX}/${PROJECT}/${ENV}/${VAR}" --multiline &>/dev/null
